package com.howtodoinjava.hibernate.annotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.OptimisticLockException;
import jakarta.persistence.Temporal;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import org.hibernate.Hibernate;
import org.hibernate.jpa.HibernatePersistenceConfiguration;
import org.hibernate.tool.schema.Action;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class AnnotationsTest {

  @TempDir
  static Path tmp;

  private EntityManagerFactory emf;
  private String ddl;
  private Long theaterId;
  private Long playId;
  private UUID performanceId;

  @BeforeEach
  void setUp() throws Exception {
    Path file = tmp.resolve("ddl-" + System.nanoTime() + ".sql");
    emf = Database.create(false, file);
    ddl = Files.readString(file).replaceAll("\\s+", " ");
    Object[] ids = emf.callInTransaction(em -> {
      Theater theater = new Theater("Globe", 300,
          new Address("21 New Globe Walk", "London", "SE1 9DT"),
          new BoxOffice("020 7401 9919", "box@globe.example"));
      em.persist(theater);
      Play play = new Play("Hamlet", Genre.DRAMA, 180, new BigDecimal("40.00"));
      play.setSynopsis("The prince of Denmark avenges his father.");
      play.setIntermission(true);
      play.setFeatured(true);
      em.persist(play);
      Performance evening = new Performance(play, theater,
          LocalDateTime.of(2026, 11, 7, 19, 30), "Main hall");
      em.persist(evening);
      return new Object[] {theater.getId(), play.getId(), evening.getId()};
    });
    theaterId = (Long) ids[0];
    playId = (Long) ids[1];
    performanceId = (UUID) ids[2];
  }

  @AfterEach
  void tearDown() {
    emf.close();
  }

  private Object nativeValue(String sql) {
    return emf.callInTransaction(em -> em.createNativeQuery(sql).getSingleResult());
  }

  @Test
  void entityAndTableNames() {
    assertTrue(ddl.contains("create table Theater ("));
    assertTrue(ddl.contains("create table play ("));
    assertTrue(ddl.contains("create table performance ("));
    List<String> halls = emf.callInTransaction(em ->
        em.createQuery("select s.hall from Show s", String.class).getResultList());
    assertEquals(List.of("Main hall"), halls);
    RuntimeException e = assertThrows(RuntimeException.class, () -> emf.runInTransaction(em ->
        em.createQuery("select p.hall from Performance p", String.class).getResultList()));
    System.out.println("CLASS NAME IN JPQL: " + e.getClass().getName() + ": " + e.getMessage());
    assertTrue(e.getMessage().contains("Could not resolve root entity 'Performance'"));
  }

  @Test
  void tableConstraintsIndexesAndComments() {
    assertTrue(ddl.contains("constraint uk_hall_time unique (theater_id, hall, starts_at)"));
    assertTrue(ddl.contains("create index idx_starts_at on performance (starts_at)"));
    assertTrue(ddl.contains("create index idx_play_genre on play (genre)"));
    assertTrue(ddl.contains("comment on table play is 'Plays in the repertoire'"));
    assertTrue(ddl.contains("comment on column play.duration_minutes is 'Running time in minutes'"));
    assertTrue(ddl.contains("duration_minutes integer constraint ck_duration check (duration_minutes > 0)"));
  }

  @Test
  void generationStrategies() {
    assertTrue(ddl.contains("id bigint generated by default as identity"));
    assertTrue(ddl.contains("create sequence play_seq start with 1 increment by 10"));
    assertTrue(ddl.contains("id uuid not null"));
    assertEquals(1L, theaterId);
    assertEquals(1L, playId);
    assertNotNull(performanceId);
    Long secondPlayId = emf.callInTransaction(em -> {
      Play play = new Play("Macbeth", Genre.DRAMA, 150, new BigDecimal("35.00"));
      em.persist(play);
      return play.getId();
    });
    assertEquals(2L, secondPlayId);
  }

  @Test
  void columnAttributes() {
    assertTrue(ddl.contains("title varchar(120) not null unique"));
    assertTrue(ddl.contains("ticket_price numeric(6,2)"));
    assertTrue(ddl.contains("seats smallint default 100 not null"));
    assertTrue(ddl.contains("email varchar(255)"));
    assertTrue(ddl.contains("starts_at timestamp(6) not null"));
    assertEquals(new BigDecimal("40.00"), nativeValue("select ticket_price from play"));
  }

  @Test
  void nullableFalseIsCheckedBeforeInsert() {
    RuntimeException e = assertThrows(RuntimeException.class, () ->
        emf.runInTransaction(em -> em.persist(new Play(null, Genre.COMEDY, 90, BigDecimal.TEN))));
    System.out.println("NULL TITLE: " + e.getClass().getName() + ": " + e.getMessage());
    assertTrue(e instanceof org.hibernate.PropertyValueException);
    assertTrue(e.getMessage().startsWith("not-null property references a null or transient value"));
    assertEquals(0L, (long) emf.callInTransaction(em ->
        em.createQuery("select count(*) from Play where title is null", Long.class).getSingleResult()));
  }

  @Test
  void uniqueIsEnforcedByTheDatabase() {
    RuntimeException e = assertThrows(RuntimeException.class, () ->
        emf.runInTransaction(em -> em.persist(new Play("Hamlet", Genre.DRAMA, 170, BigDecimal.TEN))));
    System.out.println("DUPLICATE TITLE: " + e.getClass().getName() + ": " + e.getMessage());
    assertTrue(e.getMessage().contains("Unique index or primary key violation"));
  }

  @Test
  void readOnlyForeignKeyCopy() {
    Long copy = emf.callInTransaction(em -> em.find(Performance.class, performanceId).getPlayId());
    assertEquals(playId, copy);
  }

  @Test
  void duplicateColumnWithoutInsertableFalseFails() {
    Exception e = assertThrows(Exception.class, () ->
        new HibernatePersistenceConfiguration("broken")
            .managedClasses(Play.class, DuplicateColumnShow.class)
            .jdbcUrl("jdbc:h2:mem:broken")
            .jdbcCredentials("sa", "")
            .schemaToolingAction(Action.CREATE_DROP)
            .createEntityManagerFactory());
    Throwable root = e;
    while (root.getCause() != null) {
      root = root.getCause();
    }
    System.out.println("DUPLICATE COLUMN: " + root.getClass().getName() + ": " + root.getMessage());
    assertTrue(root instanceof org.hibernate.MappingException);
    assertTrue(root.getMessage().startsWith("Column 'play_id' is duplicated in mapping for entity"));
  }

  @Test
  void transientFieldIsNotStored() {
    assertFalse(ddl.contains("featured"));
    boolean featured = emf.callInTransaction(em -> em.find(Play.class, playId).isFeatured());
    assertFalse(featured);
  }

  @Test
  void enumeratedOrdinalStringAndEnumeratedValue() {
    assertTrue(ddl.contains("status tinyint check ((status between 0 and 2))"));
    assertTrue(ddl.contains("genre enum ('COMEDY','DRAMA','MUSICAL')"));
    assertTrue(ddl.contains("language varchar(2) check ((language in ('hi','en')))"));
    assertEquals("DRAMA", nativeValue("select genre from play"));
    assertEquals(0, ((Number) nativeValue("select status from performance")).intValue());
    assertEquals(Status.SCHEDULED.ordinal(), 0);
    assertEquals("en", nativeValue("select language from performance"));
    emf.runInTransaction(em -> {
      Performance p = em.find(Performance.class, performanceId);
      p.setStatus(Status.CANCELLED);
      p.setLanguage(Language.HINDI);
    });
    assertEquals(2, ((Number) nativeValue("select status from performance")).intValue());
    assertEquals("hi", nativeValue("select language from performance"));
    assertEquals(Language.HINDI,
        emf.callInTransaction(em -> em.find(Performance.class, performanceId).getLanguage()));
  }

  @Test
  void lobWithLazyBasicIsLoadedWithoutEnhancement() {
    assertTrue(ddl.contains("synopsis clob"));
    boolean loaded = emf.callInTransaction(em ->
        Hibernate.isPropertyInitialized(em.find(Play.class, playId), "synopsis"));
    assertTrue(loaded);
  }

  @Test
  void temporalIsDeprecated() {
    Deprecated deprecated = Temporal.class.getAnnotation(Deprecated.class);
    assertNotNull(deprecated);
    assertEquals("3.2", deprecated.since());
  }

  @Test
  void embeddedColumnsAndAttributeOverride() {
    assertTrue(ddl.contains("postal_code varchar(10)"));
    assertTrue(ddl.contains("city varchar(50)"));
    assertTrue(ddl.contains("street varchar(100)"));
    assertTrue(ddl.contains("phone varchar(255)"));
    assertFalse(ddl.contains(" zip "));
    Theater globe = emf.callInTransaction(em -> em.find(Theater.class, theaterId));
    assertEquals("SE1 9DT", globe.getAddress().getZip());
    assertEquals("020 7401 9919", globe.getBoxOffice().phone());
    assertEquals("SE1 9DT", nativeValue("select postal_code from Theater"));
  }

  @Test
  void versionIncrementsAndDetectsConflicts() {
    assertTrue(ddl.contains("version integer not null"));
    assertEquals(0, ((Number) nativeValue("select version from play")).intValue());
    Play stale = emf.callInTransaction(em -> em.find(Play.class, playId));
    emf.runInTransaction(em -> em.find(Play.class, playId).setTicketPrice(new BigDecimal("45.00")));
    assertEquals(1, ((Number) nativeValue("select version from play")).intValue());
    stale.setTicketPrice(new BigDecimal("50.00"));
    RuntimeException e = assertThrows(OptimisticLockException.class, () ->
        emf.runInTransaction(em -> em.merge(stale)));
    System.out.println("STALE: " + e.getClass().getName() + ": " + e.getMessage());
    assertTrue(e.getMessage().startsWith("Row was already updated or deleted by another transaction"));
  }

  @Test
  void converterStoresYesNo() {
    assertTrue(ddl.contains("intermission varchar(1)"));
    assertEquals("Y", String.valueOf(nativeValue("select intermission from play")));
    boolean intermission = emf.callInTransaction(em -> em.find(Play.class, playId).isIntermission());
    assertTrue(intermission);
  }

  @Test
  void propertyAccessStoresGetterValue() {
    assertEquals("hamlet", nativeValue("select slug from play"));
    emf.runInTransaction(em -> em.find(Play.class, playId).setTitle("Hamlet Live"));
    assertEquals("hamlet-live", nativeValue("select slug from play"));
  }
}
