org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.log.org.hibernate.orm.connections.pooling=info
org.slf4j.simpleLogger.log.org.hibernate.orm.connections.pooling.c3p0=info
org.slf4j.simpleLogger.log.com.mchange=info
