package com.howtodoinjava.hibernate.hsqldbcast;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.ParameterMode;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import org.hibernate.tool.schema.Action;

public class CastErrorDemo {

  static final String WRONG_INSERT = "insert into bus_pass (passNumber, zone, holderName) values (?, ?, ?)";
  static final String FIXED_INSERT = "insert into bus_pass (passNumber, holderName, zone) values (?, ?, ?)";

  static final String WRONG_PROCEDURE = """
      CREATE PROCEDURE add_bus_pass(IN p_number VARCHAR(20), IN p_holder VARCHAR(50), IN p_zone INTEGER)
        MODIFIES SQL DATA
      BEGIN ATOMIC
        INSERT INTO bus_pass (passNumber, zone, holderName) VALUES (p_number, p_holder, p_zone);
      END""";
  static final String FIXED_PROCEDURE = WRONG_PROCEDURE.replace(
      "(passNumber, zone, holderName)", "(passNumber, holderName, zone)");

  static final String[] MIGRATION = {
      "alter table bus_pass alter column type set data type varchar(20)",
      "update bus_pass set type = case type when '0' then 'MONTHLY' when '1' then 'WEEKLY' when '2' then 'STUDENT' end"
  };

  static final String VALIDATION_MESSAGE = "Schema validation: wrong column type encountered in column [type] "
      + "in table [bus_pass]; found [tinyint (Types#TINYINT)], but expecting [varchar(255) (Types#VARCHAR)]";

  static final String ORDINAL_TABLE = "create table bus_pass (id bigint generated by default as identity "
      + "primary key, passNumber varchar(255), holderName varchar(255), zone integer not null, validUntil date, "
      + "type tinyint)";

  public static void seed(EntityManagerFactory emf) {
    emf.runInTransaction(em -> {
      em.persist(new BusPass("A12", "Lokesh", 2, LocalDate.of(2026, 12, 31), PassType.MONTHLY));
      em.persist(new BusPass("B7", "Alex", 3, LocalDate.of(2026, 10, 31), PassType.WEEKLY));
    });
  }

  public static void addBusPass(EntityManager em, String number, String holder, int zone) {
    em.createStoredProcedureQuery("add_bus_pass")
        .registerStoredProcedureParameter("p_number", String.class, ParameterMode.IN)
        .registerStoredProcedureParameter("p_holder", String.class, ParameterMode.IN)
        .registerStoredProcedureParameter("p_zone", Integer.class, ParameterMode.IN)
        .setParameter("p_number", number)
        .setParameter("p_holder", holder)
        .setParameter("p_zone", zone)
        .execute();
  }

  private static void step(String title) {
    System.out.println();
    System.out.println("=== " + title);
  }

  private static void attempt(Runnable action) {
    try {
      action.run();
    } catch (RuntimeException e) {
      RootCause.chain(e).forEach(line -> System.out.println("  " + line));
      SQLException sql = RootCause.sqlException(e);
      if (sql != null) {
        System.out.println("  SQLState " + sql.getSQLState() + ", error code " + sql.getErrorCode());
      }
    }
  }

  private static void print(EntityManagerFactory emf, String sql, Object... params) {
    attempt(() -> emf.runInTransaction(em -> {
      var query = em.createNativeQuery(sql, BusPass.class);
      for (int i = 0; i < params.length; i++) {
        query.setParameter(i + 1, params[i]);
      }
      System.out.println("  result: " + query.getResultList());
    }));
  }

  public static void main(String[] args) {
    String url = Database.hsqldb("passes");
    try (EntityManagerFactory emf = Database.create(url, Action.CREATE_DROP, true, BusPass.class)) {
      seed(emf);

      step("1.1 String parameter for the numeric column zone");
      print(emf, "select * from bus_pass where zone = ?", "A12");

      step("1.2 String literal for the numeric column zone");
      print(emf, "select * from bus_pass where zone = 'A12'");

      step("1.3 A numeric String is converted");
      print(emf, "select * from bus_pass where zone = ?", "2");

      step("1.4 HQL checks the parameter type");
      attempt(() -> emf.runInTransaction(em ->
          em.createQuery("from BusPass p where p.zone = :zone", BusPass.class).setParameter("zone", "A12")));

      step("1.5 HQL checks the literal type");
      attempt(() -> emf.runInTransaction(em ->
          em.createQuery("from BusPass p where p.zone = 'A12'", BusPass.class)));

      step("1.6 Fix: query the right column, or bind an int");
      print(emf, "select * from bus_pass where passNumber = ?", "A12");
      print(emf, "select * from bus_pass where zone = ?", 2);

      step("3.1 Date string dd/MM/yyyy");
      print(emf, "select * from bus_pass where validUntil < ?", "30/11/2026");

      step("3.2 Fix: parse the date in Java");
      LocalDate until = LocalDate.parse("30/11/2026", DateTimeFormatter.ofPattern("dd/MM/yyyy"));
      print(emf, "select * from bus_pass where validUntil < ?", until);

      step("4.1 INSERT with the column list in another order than the values");
      attempt(() -> emf.runInTransaction(em -> em.createNativeQuery(WRONG_INSERT)
          .setParameter(1, "C3").setParameter(2, "Maria").setParameter(3, 1).executeUpdate()));

      step("4.2 Stored procedure with the same mistake");
      Database.execute(url, WRONG_PROCEDURE);
      attempt(() -> emf.runInTransaction(em -> addBusPass(em, "C3", "Maria", 1)));

      step("4.3 Fix: same order in the column list and the values");
      Database.execute(url, "drop procedure add_bus_pass", FIXED_PROCEDURE);
      emf.runInTransaction(em -> addBusPass(em, "C3", "Maria", 1));
      print(emf, "select * from bus_pass where passNumber = ?", "C3");
    }

    step("2.1 @Enumerated(STRING) on a tinyint column created for ORDINAL");
    String legacyUrl = Database.hsqldb("legacy");
    Database.execute(legacyUrl, ORDINAL_TABLE,
        "insert into bus_pass (passNumber, holderName, zone, validUntil, type) values ('A12', 'Lokesh', 2, '2026-12-31', 0)");
    try (EntityManagerFactory legacy = Database.create(legacyUrl, Action.NONE, true, BusPass.class)) {
      attempt(() -> legacy.runInTransaction(em ->
          em.persist(new BusPass("C3", "Maria", 1, LocalDate.of(2026, 12, 31), PassType.STUDENT))));
    }

    step("2.2 Schema validation finds the mismatch at startup");
    attempt(() -> Database.create(legacyUrl, Action.VALIDATE, false, BusPass.class).close());

    step("2.3 Fix: migrate the column to names");
    Database.execute(legacyUrl, MIGRATION);
    try (EntityManagerFactory fixed = Database.create(legacyUrl, Action.VALIDATE, true, BusPass.class)) {
      fixed.runInTransaction(em ->
          em.persist(new BusPass("C3", "Maria", 1, LocalDate.of(2026, 12, 31), PassType.STUDENT)));
      fixed.runInTransaction(em -> System.out.println("  result: "
          + em.createQuery("from BusPass order by id", BusPass.class).getResultList()));
    }
  }
}
